# This file was generated by CMake because it detected TRY_RUN() commands
# in crosscompiling mode. It will be overwritten by the next CMake run.
# Copy it to a safe location, set the variables to appropriate values
# and use it then to preset the CMake cache (using -C).


# COMPILER_WORKS_EXITCODE
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set COMPILER_WORKS_EXITCODE to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# COMPILER_WORKS_EXITCODE__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set COMPILER_WORKS_EXITCODE__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The COMPILER_WORKS_COMPILED variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/pentaxmedical/work/pt/_mpsoc/CMakeFiles/CMakeTmp/src.c
# Executable    : /home/pentaxmedical/work/pt/_mpsoc/CMakeFiles/cmTC_9ca6a-COMPILER_WORKS_EXITCODE
# Run arguments : 
#    Called from: [3]	/usr/local/share/cmake-3.16/Modules/CheckCSourceRuns.cmake
#                 [2]	/home/pentaxmedical/work/pt/pytorch/cmake/MiscCheck.cmake
#                 [1]	/home/pentaxmedical/work/pt/pytorch/CMakeLists.txt

set( COMPILER_WORKS_EXITCODE 
     "PLEASE_FILL_OUT-FAILED_TO_RUN"
     CACHE STRING "Result from TRY_RUN" FORCE)

set( COMPILER_WORKS_EXITCODE__TRYRUN_OUTPUT 
     "PLEASE_FILL_OUT-NOTFOUND"
     CACHE STRING "Output from TRY_RUN" FORCE)


# BLAS_F2C_DOUBLE_WORKS_EXITCODE
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set BLAS_F2C_DOUBLE_WORKS_EXITCODE to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# BLAS_F2C_DOUBLE_WORKS_EXITCODE__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set BLAS_F2C_DOUBLE_WORKS_EXITCODE__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The BLAS_F2C_DOUBLE_WORKS_COMPILED variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/pentaxmedical/work/pt/_mpsoc/CMakeFiles/CMakeTmp/src.c
# Executable    : /home/pentaxmedical/work/pt/_mpsoc/CMakeFiles/cmTC_90a90-BLAS_F2C_DOUBLE_WORKS_EXITCODE
# Run arguments : 
#    Called from: [4]	/usr/local/share/cmake-3.16/Modules/CheckCSourceRuns.cmake
#                 [3]	/home/pentaxmedical/work/pt/pytorch/cmake/Modules/FindBLAS.cmake
#                 [2]	/home/pentaxmedical/work/pt/pytorch/cmake/Dependencies.cmake
#                 [1]	/home/pentaxmedical/work/pt/pytorch/CMakeLists.txt

set( BLAS_F2C_DOUBLE_WORKS_EXITCODE 
     "PLEASE_FILL_OUT-FAILED_TO_RUN"
     CACHE STRING "Result from TRY_RUN" FORCE)

set( BLAS_F2C_DOUBLE_WORKS_EXITCODE__TRYRUN_OUTPUT 
     "PLEASE_FILL_OUT-NOTFOUND"
     CACHE STRING "Output from TRY_RUN" FORCE)


# BLAS_F2C_FLOAT_WORKS_EXITCODE
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set BLAS_F2C_FLOAT_WORKS_EXITCODE to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# BLAS_F2C_FLOAT_WORKS_EXITCODE__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set BLAS_F2C_FLOAT_WORKS_EXITCODE__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The BLAS_F2C_FLOAT_WORKS_COMPILED variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/pentaxmedical/work/pt/_mpsoc/CMakeFiles/CMakeTmp/src.c
# Executable    : /home/pentaxmedical/work/pt/_mpsoc/CMakeFiles/cmTC_e7dda-BLAS_F2C_FLOAT_WORKS_EXITCODE
# Run arguments : 
#    Called from: [4]	/usr/local/share/cmake-3.16/Modules/CheckCSourceRuns.cmake
#                 [3]	/home/pentaxmedical/work/pt/pytorch/cmake/Modules/FindBLAS.cmake
#                 [2]	/home/pentaxmedical/work/pt/pytorch/cmake/Dependencies.cmake
#                 [1]	/home/pentaxmedical/work/pt/pytorch/CMakeLists.txt

set( BLAS_F2C_FLOAT_WORKS_EXITCODE 
     "PLEASE_FILL_OUT-FAILED_TO_RUN"
     CACHE STRING "Result from TRY_RUN" FORCE)

set( BLAS_F2C_FLOAT_WORKS_EXITCODE__TRYRUN_OUTPUT 
     "PLEASE_FILL_OUT-NOTFOUND"
     CACHE STRING "Output from TRY_RUN" FORCE)


# BLAS_USE_CBLAS_DOT_EXITCODE
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set BLAS_USE_CBLAS_DOT_EXITCODE to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# BLAS_USE_CBLAS_DOT_EXITCODE__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set BLAS_USE_CBLAS_DOT_EXITCODE__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The BLAS_USE_CBLAS_DOT_COMPILED variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/pentaxmedical/work/pt/_mpsoc/CMakeFiles/CMakeTmp/src.c
# Executable    : /home/pentaxmedical/work/pt/_mpsoc/CMakeFiles/cmTC_c2a3c-BLAS_USE_CBLAS_DOT_EXITCODE
# Run arguments : 
#    Called from: [4]	/usr/local/share/cmake-3.16/Modules/CheckCSourceRuns.cmake
#                 [3]	/home/pentaxmedical/work/pt/pytorch/cmake/Modules/FindBLAS.cmake
#                 [2]	/home/pentaxmedical/work/pt/pytorch/cmake/Dependencies.cmake
#                 [1]	/home/pentaxmedical/work/pt/pytorch/CMakeLists.txt

set( BLAS_USE_CBLAS_DOT_EXITCODE 
     "PLEASE_FILL_OUT-FAILED_TO_RUN"
     CACHE STRING "Result from TRY_RUN" FORCE)

set( BLAS_USE_CBLAS_DOT_EXITCODE__TRYRUN_OUTPUT 
     "PLEASE_FILL_OUT-NOTFOUND"
     CACHE STRING "Output from TRY_RUN" FORCE)

